//^                                                      CHAPTER 1: INTRODUCTION TO JAVA                                                                  //

/* SO BASICALLY THIS WILL BE OUR FIRST INTRODUCTION TO JAVA SCRIPT WE ARE GOING TO TALK ABOUT WHAT WE GONNA COVER IN THIS LANG AND ELSE WE WILL TRY TO MAKE 
THINGS EASY FOR YOU IN CASE YOU NEED ME TO PROVIDE HELP FOR YOU CAN JUST PING ME ON MY MAIL - "tanmay.w119@gmail.com". HERE I WILL HELP YOU TO WRITE DOWN YOUR
FIRST EVER JAVA SCRIPT CODE TO BUILDING PROJECTS. #HAPPY CODING */


//& CHAPTER'S TO BE COVERED IN THIS SERIES //
/* CHAPTER 01: INTRODUCTION TO JAVA
   CHAPTER 02: VARIABLES AND DATA TYPES
   CHAPTER 03: OPERATORS & CONDITIONAL STATEMENTS
   CHAPTER 04: LOOPS & STRINGS
   CHAPTER 05: ARRAYS
   CHAPTER 06: FUNCTIONS
   CHAPTER 07: (DOM-PART 1)
   CHAPTER 08: (DOM-PART 2)
   CHAPTER 09: EVENTS IN JAVASCRIPT
   CHAPTER 10: (BUILDING A PROJECT 1 IN JAVASCRIPT)
   CHAPTER 11: CLASSES & OBJECTS
   CHAPTER 12: CALLBACKS, PROMISES & ASYNC/AWAIT
   CHAPTER 13: FETCH API */

/* SO BASICALLY THIS IS THE FIRST CHAPTER OF THIS SERIES AND IN THIS CHAPTER WE WILL TALK ABOUT WHAT IS JAVASCRIPT, WHAT IS IT USED FOR, HOW TO USE IT AND ELSE. */

//~ let's start with the first chapter of this series //

//& WHAT IS JAVASCRIPT? //

/* 1. JAVASCRIPT IS A PROGRAMMING LANGUAGE THAT IS USED TO MAKE WEB PAGES INTERACTIVE. IT CAN BE USED TO UPDATE AND CHANGE BOTH HTML AND CSS. 
IT CAN ALSO BE USED TO CALCULATE, MANIPULATE AND VALIDATE DATA. 

 2. JAVASCRIPT IS A HIGH-LEVEL, INTERPRETED PROGRAMMING LANGUAGE THAT IS PRIMARILY USED FOR CREATING DYNAMIC AND INTERACTIVE CONTENT ON THE WEB. 
IT IS ONE OF THE CORE TECHNOLOGIES OF THE WORLD WIDE WEB, ALONGSIDE HTML AND CSS. JAVASCRIPT ENABLES DEVELOPERS TO IMPLEMENT COMPLEX FEATURES ON 
WEB PAGES, SUCH AS ANIMATIONS, FORM VALIDATION, INTERACTIVE MAPS, AND REAL-TIME UPDATES. 

3. JAVASCRIPT IS A VERSATILE LANGUAGE THAT CAN BE USED FOR BOTH CLIENT-SIDE (FRONT-END) AND SERVER-SIDE (BACK-END) DEVELOPMENT.ON THE CLIENT-SIDE, 
JAVASCRIPT RUNS IN THE USER'S WEB BROWSER AND ALLOWS DEVELOPERS TO CREATE INTERACTIVE ELEMENTS, MANIPULATE THE DOM (DOCUMENT OBJECT MODEL), AND HANDLE 
EVENTS SUCH AS CLICKS AND FORM SUBMISSIONS.ON THE SERVER-SIDE, JAVASCRIPT CAN BE USED WITH ENVIRONMENTS LIKE NODE.JS TO BUILD SCALABLE NETWORK APPLICATIONS, 
HANDLE DATABASE OPERATIONS, AND CREATE RESTFUL APIs.

4. JAVASCRIPT IS AN ESSENTIAL SKILL FOR WEB DEVELOPMENT, AND IT IS WIDELY SUPPORTED ACROSS ALL MODERN WEB BROWSERS. IT HAS A LARGE ECOSYSTEM OF 
LIBRARIES AND FRAMEWORKS, SUCH AS REACT, ANGULAR, AND VUE.JS, WHICH HELP DEVELOPERS BUILD COMPLEX APPLICATIONS MORE EFFICIENTLY. 

5. IN SUMMARY, JAVASCRIPT IS A POWERFUL AND FLEXIBLE LANGUAGE THAT PLAYS A CRUCIAL ROLE IN MODERN WEB DEVELOPMENT, ENABLING DEVELOPERS TO 
CREATE RICH, INTERACTIVE EXPERIENCES FOR USERS. */

//& WHAT IS JAVASCRIPT USED FOR? //

/* JAVASCRIPT IS USED FOR CREATING DYNAMIC AND INTERACTIVE WEB PAGES. IT CAN BE USED TO VALIDATE FORM INPUTS, CREATE ANIMATIONS, HANDLE EVENTS, 
AND MANIPULATE THE DOM. JAVASCRIPT CAN ALSO BE USED FOR SERVER-SIDE DEVELOPMENT USING NODE.JS.

JAVASCRIPT IS USED FOR A WIDE RANGE OF PURPOSES IN WEB DEVELOPMENT, INCLUDING:

1. CLIENT-SIDE SCRIPTS: JAVASCRIPT IS PRIMARILY USED TO CREATE CLIENT-SIDE SCRIPTS THAT RUN IN THE USER'S WEB BROWSER. THIS ALLOWS DEVELOPERS TO 
CREATE INTERACTIVE ELEMENTS ON WEB PAGES, SUCH AS DROPDOWN MENUS, SLIDERS, AND MODALS.

2. FORM VALIDATION: JAVASCRIPT CAN BE USED TO VALIDATE USER INPUT IN FORMS BEFORE IT IS SUBMITTED TO THE SERVER. THIS HELPS IMPROVE USER EXPERIENCE AND 
REDUCE SERVER LOAD.

3. ANIMATIONS AND EFFECTS: JAVASCRIPT CAN BE USED TO CREATE ANIMATIONS AND VISUAL EFFECTS ON WEB PAGES, ENHANCING THE USER EXPERIENCE.

4. DOM MANIPULATION: JAVASCRIPT ALLOWS DEVELOPERS TO ACCESS AND MANIPULATE THE DOCUMENT OBJECT MODEL (DOM), ENABLING THEM TO CHANGE THE 
CONTENT AND STRUCTURE OF WEB PAGES DYNAMICALLY.

5. EVENT HANDLING: JAVASCRIPT CAN BE USED TO HANDLE EVENTS SUCH AS CLICKS, HOVERING, AND FORM SUBMISSIONS, ALLOWING DEVELOPERS TO CREATE 
INTERACTIVE USER INTERFACES.

6. SERVER-SIDE DEVELOPMENT: WITH THE INTRODUCTION OF NODE.JS, JAVASCRIPT CAN ALSO BE USED FOR SERVER-SIDE DEVELOPMENT, ALLOWING DEVELOPERS TO BUILD 
FULL-STACK APPLICATIONS USING A SINGLE LANGUAGE.

7. GAME DEVELOPMENT: JAVASCRIPT CAN BE USED TO CREATE BROWSER-BASED GAMES, UTILIZING HTML5 CANVAS AND OTHER WEB TECHNOLOGIES.

8. MOBILE APP DEVELOPMENT: JAVASCRIPT FRAMEWORKS LIKE REACT NATIVE ENABLE DEVELOPERS TO BUILD CROSS-PLATFORM MOBILE APPLICATIONS USING JAVASCRIPT.

9. DATA VISUALIZATION: JAVASCRIPT LIBRARIES SUCH AS D3.JS AND CHART.JS ALLOW DEVELOPERS TO CREATE INTERACTIVE DATA VISUALIZATIONS AND CHARTS. */  
    