//^                                                      CHAPTER 1: INTRODUCTION TO JAVA                                                                  //

/* SO BASICALLY THIS WILL BE OUR FIRST INTRODUCTION TO JAVA SCRIPT WE ARE GOING TO TALK ABOUT WHAT WE GONNA COVER IN THIS LANG AND ELSE WE WILL TRY TO MAKE 
THINGS EASY FOR YOU IN CASE YOU NEED ME TO PROVIDE HELP FOR YOU CAN JUST PING ME ON MY MAIL - "tanmay.w119@gmail.com". HERE I WILL HELP YOU TO WRITE DOWN YOUR
FIRST EVER JAVA SCRIPT CODE TO BUILDING PROJECTS. #HAPPY CODING */


//& CHAPTER'S TO BE COVERED IN THIS SERIES //
/* CHAPTER 01: INTRODUCTION TO JAVA
   CHAPTER 02: VARIABLES AND DATA TYPES
   CHAPTER 03: OPERATORS & CONDITIONAL STATEMENTS
   CHAPTER 04: LOOPS & STRINGS
   CHAPTER 05: ARRAYS
   CHAPTER 06: FUNCTIONS
   CHAPTER 07: (DOM-PART 1)
   CHAPTER 08: (DOM-PART 2)
   CHAPTER 09: EVENTS IN JAVASCRIPT
   CHAPTER 10: (BUILDING A PROJECT 1 IN JAVASCRIPT)
   CHAPTER 11: CLASSES & OBJECTS
   CHAPTER 12: CALLBACKS, PROMISES & ASYNC/AWAIT
   CHAPTER 13: FETCH API */

/* SO BASICALLY THIS IS THE FIRST CHAPTER OF THIS SERIES AND IN THIS CHAPTER WE WILL TALK ABOUT WHAT IS JAVASCRIPT, WHAT IS IT USED FOR, HOW TO USE IT AND ELSE. */

//~ let's start with the first chapter of this series //

//& WHAT IS JAVASCRIPT? //

/* 1. JAVASCRIPT IS A PROGRAMMING LANGUAGE THAT IS USED TO MAKE WEB PAGES INTERACTIVE. IT CAN BE USED TO UPDATE AND CHANGE BOTH HTML AND CSS. 
IT CAN ALSO BE USED TO CALCULATE, MANIPULATE AND VALIDATE DATA. 

 2. JAVASCRIPT IS A HIGH-LEVEL, INTERPRETED PROGRAMMING LANGUAGE THAT IS PRIMARILY USED FOR CREATING DYNAMIC AND INTERACTIVE CONTENT ON THE WEB. 
IT IS ONE OF THE CORE TECHNOLOGIES OF THE WORLD WIDE WEB, ALONGSIDE HTML AND CSS. JAVASCRIPT ENABLES DEVELOPERS TO IMPLEMENT COMPLEX FEATURES ON 
WEB PAGES, SUCH AS ANIMATIONS, FORM VALIDATION, INTERACTIVE MAPS, AND REAL-TIME UPDATES. 

3. JAVASCRIPT IS A VERSATILE LANGUAGE THAT CAN BE USED FOR BOTH CLIENT-SIDE (FRONT-END) AND SERVER-SIDE (BACK-END) DEVELOPMENT.ON THE CLIENT-SIDE, 
JAVASCRIPT RUNS IN THE USER'S WEB BROWSER AND ALLOWS DEVELOPERS TO CREATE INTERACTIVE ELEMENTS, MANIPULATE THE DOM (DOCUMENT OBJECT MODEL), AND HANDLE 
EVENTS SUCH AS CLICKS AND FORM SUBMISSIONS.ON THE SERVER-SIDE, JAVASCRIPT CAN BE USED WITH ENVIRONMENTS LIKE NODE.JS TO BUILD SCALABLE NETWORK APPLICATIONS, 
HANDLE DATABASE OPERATIONS, AND CREATE RESTFUL APIs.

4. JAVASCRIPT IS AN ESSENTIAL SKILL FOR WEB DEVELOPMENT, AND IT IS WIDELY SUPPORTED ACROSS ALL MODERN WEB BROWSERS. IT HAS A LARGE ECOSYSTEM OF 
LIBRARIES AND FRAMEWORKS, SUCH AS REACT, ANGULAR, AND VUE.JS, WHICH HELP DEVELOPERS BUILD COMPLEX APPLICATIONS MORE EFFICIENTLY. 

5. IN SUMMARY, JAVASCRIPT IS A POWERFUL AND FLEXIBLE LANGUAGE THAT PLAYS A CRUCIAL ROLE IN MODERN WEB DEVELOPMENT, ENABLING DEVELOPERS TO 
CREATE RICH, INTERACTIVE EXPERIENCES FOR USERS. */

//& WHAT IS JAVASCRIPT USED FOR? //

/* JAVASCRIPT IS USED FOR CREATING DYNAMIC AND INTERACTIVE WEB PAGES. IT CAN BE USED TO VALIDATE FORM INPUTS, CREATE ANIMATIONS, HANDLE EVENTS, 
AND MANIPULATE THE DOM. JAVASCRIPT CAN ALSO BE USED FOR SERVER-SIDE DEVELOPMENT USING NODE.JS.

JAVASCRIPT IS USED FOR A WIDE RANGE OF PURPOSES IN WEB DEVELOPMENT, INCLUDING:

1. CLIENT-SIDE SCRIPTS: JAVASCRIPT IS PRIMARILY USED TO CREATE CLIENT-SIDE SCRIPTS THAT RUN IN THE USER'S WEB BROWSER. THIS ALLOWS DEVELOPERS TO 
CREATE INTERACTIVE ELEMENTS ON WEB PAGES, SUCH AS DROPDOWN MENUS, SLIDERS, AND MODALS.

2. FORM VALIDATION: JAVASCRIPT CAN BE USED TO VALIDATE USER INPUT IN FORMS BEFORE IT IS SUBMITTED TO THE SERVER. THIS HELPS IMPROVE USER EXPERIENCE AND 
REDUCE SERVER LOAD.

3. ANIMATIONS AND EFFECTS: JAVASCRIPT CAN BE USED TO CREATE ANIMATIONS AND VISUAL EFFECTS ON WEB PAGES, ENHANCING THE USER EXPERIENCE.

4. DOM MANIPULATION: JAVASCRIPT ALLOWS DEVELOPERS TO ACCESS AND MANIPULATE THE DOCUMENT OBJECT MODEL (DOM), ENABLING THEM TO CHANGE THE 
CONTENT AND STRUCTURE OF WEB PAGES DYNAMICALLY.

5. EVENT HANDLING: JAVASCRIPT CAN BE USED TO HANDLE EVENTS SUCH AS CLICKS, HOVERING, AND FORM SUBMISSIONS, ALLOWING DEVELOPERS TO CREATE 
INTERACTIVE USER INTERFACES.

6. SERVER-SIDE DEVELOPMENT: WITH THE INTRODUCTION OF NODE.JS, JAVASCRIPT CAN ALSO BE USED FOR SERVER-SIDE DEVELOPMENT, ALLOWING DEVELOPERS TO BUILD 
FULL-STACK APPLICATIONS USING A SINGLE LANGUAGE.

7. GAME DEVELOPMENT: JAVASCRIPT CAN BE USED TO CREATE BROWSER-BASED GAMES, UTILIZING HTML5 CANVAS AND OTHER WEB TECHNOLOGIES.

8. MOBILE APP DEVELOPMENT: JAVASCRIPT FRAMEWORKS LIKE REACT NATIVE ENABLE DEVELOPERS TO BUILD CROSS-PLATFORM MOBILE APPLICATIONS USING JAVASCRIPT.

9. DATA VISUALIZATION: JAVASCRIPT LIBRARIES SUCH AS D3.JS AND CHART.JS ALLOW DEVELOPERS TO CREATE INTERACTIVE DATA VISUALIZATIONS AND CHARTS. */  

//& JAVASCRIPT IN WEB DEVELOPMENT //

/* JAVASCRIPT PLAYS A CRUCIAL ROLE IN WEB DEVELOPMENT, ENABLING DEVELOPERS TO CREATE DYNAMIC AND INTERACTIVE WEB PAGES. IT WORKS ALONGSIDE HTML AND CSS TO 
PROVIDE A RICH USER EXPERIENCE. HERE ARE SOME KEY ASPECTS OF JAVASCRIPT IN WEB DEVELOPMENT:

1. INTERACTIVITY: JAVASCRIPT ALLOWS DEVELOPERS TO ADD INTERACTIVE ELEMENTS TO WEB PAGES, SUCH AS DROPDOWN MENUS, MODALS, SLIDERS, AND FORM VALIDATION. 
THIS ENHANCES THE USER EXPERIENCE AND MAKES WEB PAGES MORE ENGAGING.

2. DOM MANIPULATION: JAVASCRIPT PROVIDES ACCESS TO THE DOCUMENT OBJECT MODEL (DOM), ALLOWING DEVELOPERS TO DYNAMICALLY CHANGE THE CONTENT AND STRUCTURE 
OF WEB PAGES BASED ON USER INTERACTIONS OR OTHER EVENTS.

3. EVENT HANDLING: JAVASCRIPT ENABLES DEVELOPERS TO HANDLE EVENTS SUCH AS CLICKS, HOVERING, AND FORM SUBMISSIONS, ALLOWING FOR REAL-TIME RESPONSES TO USER 
ACTIONS.

4. AJAX AND FETCH API: JAVASCRIPT CAN BE USED TO MAKE ASYNCHRONOUS REQUESTS TO SERVERS USING AJAX OR THE FETCH API, ENABLING DYNAMIC CONTENT UPDATES WITHOUT 
RELOADING THE ENTIRE PAGE.

5. FRONT-END FRAMEWORKS: JAVASCRIPT FRAMEWORKS LIKE REACT, ANGULAR, AND VUE.JS PROVIDE STRUCTURED APPROACHES TO BUILDING COMPLEX WEB APPLICATIONS, 
MAKING IT EASIER TO MANAGE STATE, COMPONENTS, AND ROUTING.

6. SERVER-SIDE DEVELOPMENT: WITH NODE.JS, JAVASCRIPT CAN ALSO BE USED FOR SERVER-SIDE DEVELOPMENT, ALLOWING DEVELOPERS TO BUILD FULL-STACK APPLICATIONS 
USING A SINGLE LANGUAGE.

7. CROSS-PLATFORM DEVELOPMENT: JAVASCRIPT CAN BE USED TO BUILD CROSS-PLATFORM APPLICATIONS, INCLUDING MOBILE APPS USING FRAMEWORKS LIKE REACT NATIVE 
AND DESKTOP APPS USING ELECTRON.

8. DATA VISUALIZATION: JAVASCRIPT LIBRARIES SUCH AS D3.JS AND CHART.JS ENABLE DEVELOPERS TO CREATE INTERACTIVE DATA VISUALIZATIONS AND CHARTS, 
MAKING IT EASIER TO PRESENT COMPLEX DATA IN A USER-FRIENDLY MANNER.

9. COMMUNITY AND ECOSYSTEM: JAVASCRIPT HAS A LARGE AND ACTIVE COMMUNITY, PROVIDING A WEALTH OF RESOURCES, TUTORIALS, AND OPEN-SOURCE LIBRARIES THAT HELP 
DEVELOPERS LEARN AND IMPROVE THEIR SKILLS. THE ECOSYSTEM OF TOOLS AND FRAMEWORKS CONTINUES TO GROW, MAKING JAVASCRIPT A VITAL LANGUAGE IN MODERN WEB 
DEVELOPMENT. */ 

//& HOW TO USE JAVASCRIPT? //

/* THERE ARE SEVERAL WAYS TO USE JAVASCRIPT IN WEB DEVELOPMENT. HERE ARE SOME COMMON METHODS:

1. INLINE JAVASCRIPT: YOU CAN WRITE JAVASCRIPT CODE DIRECTLY WITHIN HTML ELEMENTS USING THE "ON-EVENT" ATTRIBUTES. FOR EXAMPLE:
   <button onclick="alert('Hello, World!')">Click Me</button>

2. INTERNAL JAVASCRIPT: YOU CAN INCLUDE JAVASCRIPT CODE WITHIN A <script> TAG IN THE HEAD OR BODY SECTION OF YOUR HTML DOCUMENT. FOR EXAMPLE:
   <script>
       function greet() {
           alert('Hello, World!');
       }
   </script>

3. EXTERNAL JAVASCRIPT: YOU CAN CREATE A SEPARATE .JS FILE AND LINK IT TO YOUR HTML DOCUMENT USING THE <script> TAG WITH THE "SRC" ATTRIBUTE. 
   FOR EXAMPLE:
   <script src="script.js"></script>

4. USING JAVASCRIPT FRAMEWORKS AND LIBRARIES: YOU CAN USE POPULAR JAVASCRIPT FRAMEWORKS AND LIBRARIES LIKE REACT, ANGULAR, VUE.JS, AND JQUERY TO SIMPLIFY 
DEVELOPMENT AND ADD ADVANCED FUNCTIONALITY.

5. USING NODE.JS: FOR SERVER-SIDE DEVELOPMENT, YOU CAN USE NODE.JS TO RUN JAVASCRIPT CODE OUTSIDE OF THE BROWSER. THIS ALLOWS YOU TO BUILD FULL-STACK 
APPLICATIONS USING JAVASCRIPT.

6. USING BROWSER CONSOLE: YOU CAN TEST AND EXECUTE JAVASCRIPT CODE DIRECTLY IN THE BROWSER'S DEVELOPER CONSOLE. THIS IS USEFUL FOR QUICK TESTING AND 
DEBUGGING.

7. USING ONLINE EDITORS: THERE ARE ONLINE EDITORS LIKE JSFIDDLE, CODEPEN, AND REPL.IT WHERE YOU CAN WRITE, TEST, AND SHARE JAVASCRIPT CODE WITHOUT 
SETTING UP A LOCAL DEVELOPMENT ENVIRONMENT.

8. USING MODULES: MODERN JAVASCRIPT SUPPORTS MODULES, ALLOWING YOU TO ORGANIZE YOUR CODE INTO SEPARATE FILES AND IMPORT THEM AS NEEDED. THIS PROMOTES 
BETTER CODE STRUCTURE AND REUSABILITY.

9. USING PACKAGE MANAGERS: YOU CAN USE PACKAGE MANAGERS LIKE NPM (NODE PACKAGE MANAGER) OR YARN TO INSTALL AND MANAGE JAVASCRIPT LIBRARIES AND DEPENDENCIES 
IN YOUR PROJECTS. THIS MAKES IT EASIER TO INCLUDE THIRD-PARTY CODE AND KEEP IT UP-TO-DATE.

10. USING BUNDLERS: TO OPTIMIZE AND PACKAGE YOUR JAVASCRIPT CODE FOR PRODUCTION, YOU CAN USE BUNDLERS LIKE WEBPACK, ROLLUP, OR PARCEL. THESE TOOLS HELP 
COMBINE AND MINIFY YOUR CODE, IMPROVING PERFORMANCE AND LOAD TIMES.

11. USING TRANSPILE TOOLS: IF YOU WANT TO USE MODERN JAVASCRIPT FEATURES THAT MAY NOT BE SUPPORTED IN ALL BROWSERS, YOU CAN USE TRANSPILE TOOLS LIKE BABEL 
TO CONVERT YOUR CODE INTO A COMPATIBLE VERSION.

12. USING TESTING FRAMEWORKS: TO ENSURE THE QUALITY AND RELIABILITY OF YOUR JAVASCRIPT CODE, YOU CAN USE TESTING FRAMEWORKS LIKE JEST, MOCHA, OR CHAI TO 
WRITE UNIT TESTS AND INTEGRATION TESTS.

13. USING LINTERS: TO MAINTAIN CONSISTENT CODE STYLE AND CATCH POTENTIAL ERRORS EARLY, YOU CAN USE LINTERS LIKE ESLINT OR JSHINT TO ANALYZE YOUR 
JAVASCRIPT CODE AND PROVIDE FEEDBACK ON BEST PRACTICES AND POTENTIAL ISSUES.*/

//& FIRST EVER JAVASCRIPT CODE //

/* NOW LET'S WRITE OUR FIRST EVER JAVASCRIPT CODE. WE WILL CREATE A SIMPLE ALERT MESSAGE THAT WILL POP UP WHEN THE PAGE LOADS. FOLLOW THESE STEPS:

1. CREATE AN HTML FILE (index.html) AND ADD THE FOLLOWING CODE:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First JavaScript Code</title>
</head>
<body>
    <h1>Welcome to My First JavaScript Code!</h1>
    <script src="script.js"></script>
</body>
</html>

2. CREATE A JAVASCRIPT FILE (script.js) AND ADD THE FOLLOWING CODE:

alert('Hello, World! This is my first JavaScript code!');

3. OPEN THE index.html FILE IN YOUR WEB BROWSER. YOU SHOULD SEE AN ALERT POP UP WITH THE MESSAGE "Hello, World! This is my first JavaScript code!" WHEN THE PAGE LOADS. */

/* CONGRATULATIONS! YOU HAVE SUCCESSFULLY WRITTEN AND EXECUTED YOUR FIRST JAVASCRIPT CODE. THIS IS JUST THE BEGINNING OF YOUR JOURNEY INTO THE WORLD OF 
JAVASCRIPT DEVELOPMENT. KEEP EXPLORING AND LEARNING TO UNLOCK THE FULL POTENTIAL OF THIS POWERFUL LANGUAGE. */

//& CONCLUSION //

/* IN THIS CHAPTER, WE HAVE COVERED THE BASICS OF JAVASCRIPT, INCLUDING WHAT IT IS, WHAT IT IS USED FOR, AND HOW TO USE IT. JAVASCRIPT IS A POWERFUL 
AND VERSATILE LANGUAGE THAT PLAYS A CRUCIAL ROLE IN MODERN WEB DEVELOPMENT. IT ENABLES DEVELOPERS TO CREATE DYNAMIC AND INTERACTIVE WEB PAGES, 
HANDLE EVENTS, MANIPULATE THE DOM, AND BUILD FULL-STACK APPLICATIONS. BY UNDERSTANDING THE FUNDAMENTALS OF JAVASCRIPT AND ITS VARIOUS USE CASES, 
YOU WILL BE WELL-PREPARED TO EMBARK ON YOUR JOURNEY AS A JAVASCRIPT DEVELOPER. #HAPPY CODING */
    