//^                                                      CHAPTER 1: INTRODUCTION TO JAVA                                                                  //

/* SO BASICALLY THIS WILL BE OUR FIRST INTRODUCTION TO JAVA SCRIPT WE ARE GOING TO TALK ABOUT WHAT WE GONNA COVER IN THIS LANG AND ELSE WE WILL TRY TO MAKE 
THINGS EASY FOR YOU IN CASE YOU NEED ME TO PROVIDE HELP FOR YOU CAN JUST PING ME ON MY MAIL - "tanmay.w119@gmail.com". HERE I WILL HELP YOU TO WRITE DOWN YOUR
FIRST EVER JAVA SCRIPT CODE TO BUILDING PROJECTS. #HAPPY CODING */


//& CHAPTER'S TO BE COVERED IN THIS SERIES //
/* CHAPTER 01: INTRODUCTION TO JAVA
   CHAPTER 02: VARIABLES AND DATA TYPES
   CHAPTER 03: OPERATORS & CONDITIONAL STATEMENTS
   CHAPTER 04: LOOPS & STRINGS
   CHAPTER 05: ARRAYS
   CHAPTER 06: FUNCTIONS
   CHAPTER 07: (DOM-PART 1)
   CHAPTER 08: (DOM-PART 2)
   CHAPTER 09: EVENTS IN JAVASCRIPT
   CHAPTER 10: (BUILDING A PROJECT 1 IN JAVASCRIPT)
   CHAPTER 11: CLASSES & OBJECTS
   CHAPTER 12: CALLBACKS, PROMISES & ASYNC/AWAIT
   CHAPTER 13: FETCH API */

        
    