//^                                                              CHAPTER 5: ARRAYS                                                                         //

//~ IN THIS CHAPTER, WE WILL LEARN ABOUT ARRAYS IN JAVASCRIPT. ARRAYS ARE USED TO STORE MULTIPLE VALUES IN A SINGLE VARIABLE. THEY PROVIDE A WAY TO ORGANIZE 
//~ AND MANAGE DATA EFFICIENTLY. WE WILL COVER ARRAY DECLARATION, ACCESSING ELEMENTS, MODIFICATION, AND COMMON ARRAY METHODS WITH EXAMPLES TO ILLUSTRATE 
//~ THEIR USAGE IN JAVASCRIPT.

//& ARRAYS IN JAVASCRIPT

/* ARRAYS ARE USED TO STORE MULTIPLE VALUES IN A SINGLE VARIABLE. THEY PROVIDE A WAY TO ORGANIZE AND MANAGE DATA EFFICIENTLY. ARRAYS CAN HOLD ELEMENTS OF 
DIFFERENT DATA TYPES, INCLUDING NUMBERS, STRINGS, OBJECTS, AND EVEN OTHER ARRAYS.

ARRAYS ARE ZERO-INDEXED, MEANING THE FIRST ELEMENT IS ACCESSED USING INDEX 0, THE SECOND ELEMENT USING INDEX 1, AND SO ON. JAVASCRIPT PROVIDES VARIOUS 
METHODS TO MANIPULATE ARRAYS, SUCH AS ADDING OR REMOVING ELEMENTS, SORTING, AND ITERATING THROUGH THE ELEMENTS. ARRAYS ARE A FUNDAMENTAL DATA STRUCTURE IN 
JAVASCRIPT AND ARE WIDELY USED IN WEB DEVELOPMENT. */ 
 